### PR TITLE
Tidy up the model associations

### PR DESCRIPTION
**Pull request by lorint**
Hi Adrian!

Thanks for the suggestion to try out **[The Brick](https://github.com/lorint/brick)** along with your Avo demo site.  Have gotten everything working, and along the way found these useful updates to the models here.  No data changes necessary -- this stuff only updates the way that associations are wired up.

For the TeamMembership things -- there's a model for the JOIN table already in place, so changed those over to a has_many :through instead of a HABTM.

For Users and Posts -- because there is only one foreign key between these two tables -- the user_id field in posts -- it didn't make sense for User to have both a has_one and a has_many over to Post.  Had removed the has_one, as well as in the UserResource the post, still leaving the posts in place.

Eager to hear what you think!

-L

### CODE REVIEW

**Comment by adrianthedev** [comment]
Hey @lorint. Apologies for the delay. I was just catching up this week.

I know the models are modeled a bit weird, but they are like that by design. It's just to showcase what Avo supports. For example, the `User` `has_one` `Post` is there to showcase and test that you can apply custom translations and that it supports a `has_one`.
The rest are like that because of that same reason. To simulate a real-world example and to showcase that Avo supports that.

The second reason why they are like that is that we test Avo's features on a `dummy` app (in https://github.com/avo-hq/avo), and we keep these two apps pretty much in sync to reference the features to other users.

I hope you don't mind me merging the PR. I'd like to keep things in sync for easier feature management.

**Comment by lorint** [comment]
> ... the models are modeled a bit weird, but they are like that by design

Would at least recommend the changes to `spouse.rb` and `person.rb` only because there is no **marriage_person_id** column in the **people** table.  The other team membership stuff should also be useful as well, but I suppose is not absolutely critical.

**Comment by adrianthedev** [comment]
Ok, that makes sense!
Could you clean up the PR to have only those changes?

**Comment by lorint** [comment]
Here you go -- have also added a carriage return at the end of the Gemfile.  (Was missing previously.)

Tempted to bring Rails up to 7.0.4, but then that's not model changes anymore :)

LMK what you think -- hopefully this works smoothly with all the other tests and such.

**Comment by adrianthedev** [comment]
Thanks @lorint.

The demo app doesn't have any tests unfortunately 😛 
The main Avo repo has a ton of tests. That's where we test Avo.

I haven't enabled tests with Rails 7 and Avo. I think there are a few gems that need different versions themselves on Rails 7 and newer versions of Ruby and I had an issue with Appraisal.

I'll probably work on that after Avo 3 launch.

**Pull request merged**
